global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['localhost:3001']
  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104'] 